task: default
source_path: data/test
exp_name: first_exp

data:
  split_train: -1
  split_test: 4
  type: Colmap
  white_background: true
  use_colmap: true

model:
  gaussian:
    sh_degree: 1
    fourier_dim: 3

train:
  iterations: 30000
  test_iterations: [7000, 30000]

optim:
  opacity_lr: 0.05
  rotation_lr: 0.001
  scaling_lr: 0.005

  lambda_dssim: 0.2
  lambda_reg: 0.1

render:
  fps: 30
